package server

import (
	"embed"
	"io/fs"
	"net/http"

	"github.com/rakunlabs/ada"
	"github.com/rakunlabs/ada/handler/folder"
)

// dist holds the built SPA. It is generated by `make build-ui`
// (pnpm build → internal/server/dist). A committed .gitkeep keeps the
// directory present so `go build` works even before the UI is generated;
// in that state only the placeholder is embedded and the SPA 404s until
// `make build-ui` runs. `all:dist` is used (not `dist/*`) so the build
// succeeds when only the dotfile placeholder is present.
//
//go:embed all:dist
var uiFS embed.FS

// folderHandler mounts the embedded SPA as the catch-all on m. API and
// data-plane routes are registered before this, so they take precedence;
// everything else (index.html, /assets/*, favicon) is served from the
// embedded bundle. SPA mode serves index.html for unknown paths so the
// hash-routed client can take over.
func folderHandler(m *ada.Mux) error {
	f, err := folder.New(&folder.Config{
		Browse:         false,
		SPA:            true,
		Index:          true,
		StripIndexName: true,
		PrefixPath:     m.Prefix(),
		CacheRegex: []*folder.RegexCacheStore{
			// Vite content-hashed bundles — safe to cache forever.
			{
				Regex:        `^index-[A-Za-z0-9_-]+\.(js|css)$`,
				CacheControl: "public, max-age=31536000, immutable",
			},
			// Root-level static images/fonts — stable filenames.
			{
				Regex:        `\.(ico|png|svg|webp|woff2?)$`,
				CacheControl: "public, max-age=604800",
			},
			// SPA shell — always revalidate so new hashed asset URLs
			// are picked up immediately after a deploy.
			{
				Regex:        `index\.html$`,
				CacheControl: "no-cache",
			},
		},
	})
	if err != nil {
		return err
	}

	uiDist, err := fs.Sub(uiFS, "dist")
	if err != nil {
		return err
	}
	f.SetFs(http.FS(uiDist))

	m.Handle("/*", f)
	return nil
}
