package alpine

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha1"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"io"
	"net/http"
	"net/http/httptest"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/rakunlabs/kutu/internal/rawfs"
	"github.com/rakunlabs/kutu/internal/rawfs/localfs"
	"github.com/rakunlabs/kutu/internal/registry"
	"github.com/rakunlabs/kutu/internal/service"
)

type stubResolver map[string]registry.Registry

func (s stubResolver) Lookup(_, repo string) (registry.Registry, bool) {
	r, ok := s[repo]
	return r, ok
}

func tarGz(t *testing.T, files map[string]string, cut bool) []byte {
	t.Helper()
	var tb bytes.Buffer
	tw := tar.NewWriter(&tb)
	for name, body := range files {
		if err := tw.WriteHeader(&tar.Header{Name: name, Mode: 0o644, Size: int64(len(body)), ModTime: time.Unix(1700000000, 0), Typeflag: tar.TypeReg}); err != nil {
			t.Fatal(err)
		}
		_, _ = tw.Write([]byte(body))
	}
	_ = tw.Close()
	raw := tb.Bytes()
	if cut {
		raw = raw[:len(raw)-1024]
	}
	var gb bytes.Buffer
	zw := gzip.NewWriter(&gb)
	_, _ = zw.Write(raw)
	_ = zw.Close()
	return gb.Bytes()
}

// buildAPK returns an .apk (signature + control + data streams) and
// the raw control stream.
func buildAPK(t *testing.T, name, ver, arch, license string) ([]byte, []byte) {
	t.Helper()
	info := strings.Join([]string{
		"# Generated by abuild",
		"pkgname = " + name,
		"pkgver = " + ver,
		"pkgdesc = test package " + name,
		"url = https://example.com/" + name,
		"builddate = 1700000000",
		"packager = Test <t@example.com>",
		"size = 4096",
		"arch = " + arch,
		"origin = " + name,
		"license = " + license,
		"depend = musl",
		"depend = so:libc.musl-x86_64.so.1",
		"provides = cmd:" + name + "=" + ver,
		"datahash = abc",
		"",
	}, "\n")
	sig := tarGz(t, map[string]string{".SIGN.RSA.builder.rsa.pub": "fake-signature"}, true)
	control := tarGz(t, map[string]string{".PKGINFO": info}, true)
	data := tarGz(t, map[string]string{"usr/bin/" + name: "#!/bin/sh\necho hi\n"}, false)
	apk := append(append(append([]byte{}, sig...), control...), data...)
	return apk, control
}

func genKeyPEM(t *testing.T) (string, *rsa.PrivateKey) {
	t.Helper()
	k, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		t.Fatal(err)
	}
	return string(pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(k)})), k
}

func newLocal(t *testing.T, name, key string) *Local {
	t.Helper()
	fs, err := localfs.New(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	deps := registry.Deps{MountRawFS: func(string) (rawfs.RawFS, error) { return fs, nil }}
	repo := &service.RegistryRepository{Name: name, Type: typ, Kind: service.RegistryKindLocal, Mount: "m", BasePath: "apk", AllowPush: true, SigningKey: key}
	r, err := NewLocalFactory()(context.Background(), deps, "default", repo)
	if err != nil {
		t.Fatal(err)
	}
	return r.(*Local)
}

func do(h http.Handler, method, p string, body []byte) *httptest.ResponseRecorder {
	r := httptest.NewRequest(method, p, bytes.NewReader(body))
	w := httptest.NewRecorder()
	h.ServeHTTP(w, r)
	return w
}

// splitStreams returns the raw bytes of each gzip member of b.
func splitStreams(t *testing.T, b []byte) [][]byte {
	t.Helper()
	var out [][]byte
	if err := walkMembers(b, nil, func(m gzipMember) bool {
		out = append(out, b[m.Start:m.End])
		return false
	}); err != nil {
		t.Fatal(err)
	}
	return out
}

func indexText(t *testing.T, b []byte) string {
	t.Helper()
	text, err := readIndex(b)
	if err != nil {
		t.Fatal(err)
	}
	return text
}

func TestParseAPK(t *testing.T) {
	apk, control := buildAPK(t, "hello", "1.0-r0", "x86_64", "MIT")
	rec, err := parseAPK(apk)
	if err != nil {
		t.Fatal(err)
	}
	sum := sha1.Sum(control)
	want := "Q1" + base64.StdEncoding.EncodeToString(sum[:])
	if rec.Checksum != want {
		t.Fatalf("checksum %s want %s", rec.Checksum, want)
	}
	if rec.Name != "hello" || rec.Version != "1.0-r0" || rec.InstalledSize != 4096 || len(rec.Depends) != 2 || rec.Size != int64(len(apk)) {
		t.Fatalf("record: %+v", rec)
	}
	if n, v, ok := splitFilename("py3-foo-bar-1.2.3_rc1-r10.apk"); !ok || n != "py3-foo-bar" || v != "1.2.3_rc1-r10" {
		t.Fatalf("split: %s %s", n, v)
	}
}

func TestLocalSignedRoundTrip(t *testing.T) {
	keyPEM, key := genKeyPEM(t)
	l := newLocal(t, "alp", keyPEM)
	apk, control := buildAPK(t, "hello", "1.0-r0", "x86_64", "MIT")
	if w := do(l, http.MethodPut, "/upload/v3.20/main", apk); w.Code != http.StatusCreated {
		t.Fatalf("upload: %d %s", w.Code, w.Body)
	}
	apk2, _ := buildAPK(t, "hello", "1.1-r0", "x86_64", "MIT")
	if w := do(l, http.MethodPut, "/upload/v3.20/main", apk2); w.Code != http.StatusCreated {
		t.Fatalf("upload2: %d %s", w.Code, w.Body)
	}

	w := do(l, http.MethodGet, "/v3.20/main/x86_64/APKINDEX.tar.gz", nil)
	if w.Code != 200 {
		t.Fatalf("index: %d", w.Code)
	}
	idx := w.Body.Bytes()
	streams := splitStreams(t, idx)
	if len(streams) != 2 {
		t.Fatalf("want signature + index streams, got %d", len(streams))
	}
	// signature stream: one cut tar entry
	zr, _ := gzip.NewReader(bytes.NewReader(streams[0]))
	sigTar, _ := io.ReadAll(zr)
	if len(sigTar)%512 != 0 || len(sigTar) != 1024 {
		t.Fatalf("signature tar must have no end blocks: %d bytes", len(sigTar))
	}
	tr := tar.NewReader(bytes.NewReader(sigTar))
	hdr, err := tr.Next()
	if err != nil || hdr.Name != ".SIGN.RSA.kutu.rsa.pub" {
		t.Fatalf("sig entry: %v %+v", err, hdr)
	}
	sig, _ := io.ReadAll(tr)
	digest := sha1.Sum(streams[1])
	if err := rsa.VerifyPKCS1v15(&key.PublicKey, crypto.SHA1, digest[:], sig); err != nil {
		t.Fatalf("signature: %v", err)
	}

	text := indexText(t, idx)
	sum := sha1.Sum(control)
	for _, want := range []string{
		"C:Q1" + base64.StdEncoding.EncodeToString(sum[:]) + "\nP:hello\nV:1.0-r0\nA:x86_64\n",
		"S:" + strconv.Itoa(len(apk)) + "\n", "I:4096\n", "L:MIT\n", "t:1700000000\n",
		"D:musl so:libc.musl-x86_64.so.1\n", "p:cmd:hello=1.0-r0\n", "V:1.1-r0\n",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("index missing %q:\n%s", want, text)
		}
	}
	if len(splitBlocks(text)) != 2 {
		t.Fatalf("want 2 records:\n%s", text)
	}

	if w := do(l, http.MethodGet, "/v3.20/main/x86_64/hello-1.0-r0.apk", nil); w.Code != 200 || !bytes.Equal(w.Body.Bytes(), apk) {
		t.Fatalf("download: %d", w.Code)
	}
	w = do(l, http.MethodGet, "/keys/kutu.rsa.pub", nil)
	if w.Code != 200 {
		t.Fatalf("key: %d", w.Code)
	}
	blk, _ := pem.Decode(w.Body.Bytes())
	pub, err := x509.ParsePKIXPublicKey(blk.Bytes)
	if err != nil || !pub.(*rsa.PublicKey).Equal(&key.PublicKey) {
		t.Fatalf("public key mismatch: %v", err)
	}

	pkgs, _ := l.ListPackages(context.Background())
	if len(pkgs) != 1 || pkgs[0].Name != "hello" || len(pkgs[0].Versions) != 2 {
		t.Fatalf("list: %+v", pkgs)
	}
	d, err := l.PackageDetail(context.Background(), "hello")
	if err != nil || d.Generic.LatestVersion != "1.1-r0" || d.Generic.License != "MIT" {
		t.Fatalf("detail: %+v %v", d, err)
	}
	info, err := l.ArtifactInfo(context.Background(), registry.ArtifactRef{Name: "hello", Version: "1.0-r0"})
	if err != nil || info.License != "MIT" || info.PublishedAt.Unix() != 1700000000 {
		t.Fatalf("info: %+v %v", info, err)
	}
	ref, ok := l.ClassifyRequest(httptest.NewRequest(http.MethodGet, "/v3.20/main/x86_64/hello-1.0-r0.apk", nil))
	if !ok || ref.Name != "hello" || ref.Version != "1.0-r0" {
		t.Fatalf("classify: %+v", ref)
	}

	if err := l.DeleteVersion(context.Background(), "hello", "1.0-r0"); err != nil {
		t.Fatal(err)
	}
	text = indexText(t, do(l, http.MethodGet, "/v3.20/main/x86_64/APKINDEX.tar.gz", nil).Body.Bytes())
	if strings.Contains(text, "V:1.0-r0") || !strings.Contains(text, "V:1.1-r0") {
		t.Fatalf("after delete:\n%s", text)
	}
	if w := do(l, http.MethodDelete, "/v3.20/main/x86_64/hello-1.1-r0.apk", nil); w.Code != http.StatusNoContent {
		t.Fatalf("http delete: %d", w.Code)
	}
	text = indexText(t, do(l, http.MethodGet, "/v3.20/main/x86_64/APKINDEX.tar.gz", nil).Body.Bytes())
	if strings.TrimSpace(text) != "" {
		t.Fatalf("index should be empty:\n%s", text)
	}
	if err := l.DeleteVersion(context.Background(), "hello", "9"); err != registry.ErrPackageNotFound {
		t.Fatalf("missing delete: %v", err)
	}
}

func TestLocalNoarchAndPromote(t *testing.T) {
	l := newLocal(t, "alp", "")
	apk, _ := buildAPK(t, "data", "2.0-r1", "noarch", "Apache-2.0")
	if w := do(l, http.MethodPut, "/upload/edge/community", apk); w.Code != http.StatusCreated {
		t.Fatalf("upload: %d %s", w.Code, w.Body)
	}
	for _, a := range defaultArches {
		w := do(l, http.MethodGet, "/edge/community/"+a+"/APKINDEX.tar.gz", nil)
		if w.Code != 200 {
			t.Fatalf("%s index: %d", a, w.Code)
		}
		if n := len(splitStreams(t, w.Body.Bytes())); n != 1 {
			t.Fatalf("unsigned index should have 1 stream, got %d", n)
		}
		if !strings.Contains(indexText(t, w.Body.Bytes()), "P:data\nV:2.0-r1\nA:noarch\n") {
			t.Fatalf("%s missing record", a)
		}
	}
	if w := do(l, http.MethodGet, "/keys/kutu.rsa.pub", nil); w.Code != 404 {
		t.Fatalf("key without signing: %d", w.Code)
	}
	dst := newLocal(t, "prod", "")
	if err := l.PromoteVersion(context.Background(), dst, "data", "2.0-r1"); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(indexText(t, do(dst, http.MethodGet, "/edge/community/x86_64/APKINDEX.tar.gz", nil).Body.Bytes()), "P:data") {
		t.Fatal("promoted index missing record")
	}
	if w := do(l, http.MethodPut, "/upload/edge/community", []byte("garbage")); w.Code != http.StatusBadRequest {
		t.Fatalf("bad apk: %d", w.Code)
	}
}

func TestRemote(t *testing.T) {
	up := newLocal(t, "up", "")
	apk, _ := buildAPK(t, "hello", "1.0-r0", "x86_64", "MIT")
	do(up, http.MethodPut, "/upload/v3.20/main", apk)
	hits := 0
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		hits++
		up.ServeHTTP(w, r)
	}))
	defer srv.Close()

	fs, _ := localfs.New(t.TempDir())
	deps := registry.Deps{MountRawFS: func(string) (rawfs.RawFS, error) { return fs, nil }}
	repo := &service.RegistryRepository{Name: "rem", Type: typ, Kind: service.RegistryKindRemote, Mount: "m", BasePath: "c", URL: srv.URL}
	reg, err := NewRemoteFactory()(context.Background(), deps, "default", repo)
	if err != nil {
		t.Fatal(err)
	}
	rr := reg.(*Remote)
	w := do(rr, http.MethodGet, "/v3.20/main/x86_64/APKINDEX.tar.gz", nil)
	if w.Code != 200 || !strings.Contains(indexText(t, w.Body.Bytes()), "P:hello") {
		t.Fatalf("remote index: %d", w.Code)
	}
	if err := rr.Prefetch(context.Background(), "hello", ""); err != nil {
		t.Fatal(err)
	}
	srv.Close()
	if w := do(rr, http.MethodGet, "/v3.20/main/x86_64/hello-1.0-r0.apk", nil); w.Code != 200 || !bytes.Equal(w.Body.Bytes(), apk) {
		t.Fatalf("cached apk: %d", w.Code)
	}
	pkgs, _ := rr.ListPackages(context.Background())
	if len(pkgs) != 1 || pkgs[0].Name != "hello" {
		t.Fatalf("remote list: %+v", pkgs)
	}
	info, err := rr.ArtifactInfo(context.Background(), registry.ArtifactRef{Name: "hello", Version: "1.0-r0"})
	if err != nil || info.License != "MIT" {
		t.Fatalf("remote info: %+v %v", info, err)
	}
	d, err := rr.PackageDetail(context.Background(), "hello")
	if err != nil || d.Generic.License != "MIT" {
		t.Fatalf("remote detail: %+v %v", d, err)
	}
	if w := do(rr, http.MethodPut, "/upload/v3.20/main", apk); w.Code != http.StatusMethodNotAllowed {
		t.Fatalf("remote write: %d", w.Code)
	}
	st, _ := rr.PurgeCache(context.Background(), registry.PurgeOptions{})
	if st.PurgedFiles != 1 {
		t.Fatalf("purge: %+v", st)
	}
}

func TestVirtualMergesIndexes(t *testing.T) {
	keyPEM, _ := genKeyPEM(t)
	a := newLocal(t, "a", keyPEM)
	b := newLocal(t, "b", "")
	apkA, _ := buildAPK(t, "alpha", "1.0-r0", "x86_64", "MIT")
	apkB, _ := buildAPK(t, "beta", "2.0-r0", "x86_64", "GPL-2.0")
	do(a, http.MethodPut, "/upload/v3.20/main", apkA)
	do(b, http.MethodPut, "/upload/v3.20/main", apkB)
	do(b, http.MethodPut, "/upload/v3.20/main", apkA)

	reg, err := NewVirtualFactory(stubResolver{"a": a, "b": b})(context.Background(), registry.Deps{}, "default",
		&service.RegistryRepository{Name: "v", Type: typ, Kind: service.RegistryKindVirtual, Members: []string{"a", "b"}})
	if err != nil {
		t.Fatal(err)
	}
	w := do(reg, http.MethodGet, "/v3.20/main/x86_64/APKINDEX.tar.gz", nil)
	if w.Code != 200 {
		t.Fatalf("virtual index: %d", w.Code)
	}
	if n := len(splitStreams(t, w.Body.Bytes())); n != 1 {
		t.Fatalf("virtual index must be unsigned, got %d streams", n)
	}
	text := indexText(t, w.Body.Bytes())
	if len(splitBlocks(text)) != 2 || !strings.Contains(text, "P:alpha") || !strings.Contains(text, "P:beta") {
		t.Fatalf("merged:\n%s", text)
	}
	if w := do(reg, http.MethodGet, "/v3.20/main/x86_64/beta-2.0-r0.apk", nil); w.Code != 200 || !bytes.Equal(w.Body.Bytes(), apkB) {
		t.Fatalf("virtual download: %d", w.Code)
	}
	pkgs, _ := reg.(registry.PackageLister).ListPackages(context.Background())
	if len(pkgs) != 2 {
		t.Fatalf("virtual list: %+v", pkgs)
	}
}
